# Generated by Django 4.1.6 on 2023-05-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTIAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_mbti',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_mbti',
        ),
    ]
